Controllers/InicioController.cs
using System.Web.Mvc;

namespace ProyectoConversion.Controllers
{
    [Authorize]
    public class InicioController : Controller
    {
        // GET: Inicio        
        public ActionResult Inicio()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@{
    ProyectoConversion.Models.Usuario usuario = HttpContext.Current.Session["Usuario"] as ProyectoConversion.Models.Usuario;
    if (usuario == null || usuario.User == null)
    {
        Response.Redirect("~/Login");
    }
    var userName = usuario.User;
}
<!DOCTYPE html>
<html>
    <head>
        <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>@ViewBag.Title - Registro de PDF del RPI</title>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.1.1/css/all.min.css" />
        @RenderSection("Styles", required: false)
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
        <script src="~/Scripts/jquery-3.7.1.min.js"></script>
    </head>
    <body class="d-flex flex-column min-vh-100 bg-light">
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm h5 bg-primary bg-opacity-75">
            <div class="container align-middle">
                <button class="btn btn-outline-info rounded-3 me-1 border-0 btn-lg">
                    @Html.ActionLink("INICIO", "Inicio", "Inicio", new { area = "" }, new { @class = "nav-link text-dark fw-bold" })
                </button>
                <button type="button" class="navbar-toggler" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" title="Alternar navegación" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse d-sm-inline-flex justify-content-sm-start">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <button class="btn btn-outline-primary rounded-3 me-1 border-0 btn-lg">
                                @Html.ActionLink("Matriculas", "Activos", "ImagenesMatriculas", new { area = "" }, new { @class = "nav-link text-dark fw-bold" })
                            </button>
                        </li>
                        <li class="nav-item">
                            <button class="btn btn-outline-primary rounded-3 me-1 border-0 btn-lg">
                                @Html.ActionLink("Departamentos", "Activos", "Departamentos", new { area = "" }, new { @class = "nav-link text-dark fw-bold" })
                            </button>
                        </li>
                        <!--
                        <li class="nav-item">
                            <button class="btn btn-outline-primary rounded-3 me-1 border-0 btn-lg">
                                @Html.ActionLink("Tomos", "Activos", "ImagenesTomosCronologicos", new { area = "" }, new { @class = "nav-link text-dark fw-bold" })
                            </button>
                        </li>
                        <li class="nav-item">
                                                    <button class="btn btn-outline-primary rounded-3 me-1 border-0 btn-lg">
                                @Html.ActionLink("Minutas", "Activos", "ImagenesMinutas", new { area = "" }, new { @class = "nav-link text-dark fw-bold" })
                            </button>
                        </li>
                        -->
                    </ul>
                    <ul class="navbar-nav flex-column">
                        <li class="nav-item d-none d-sm-block nav-link navbar-text text-light">@userName</li>
                        <li class="nav-item d-none d-sm-block">@Html.ActionLink("Cerrar Sesión", "Logout", "Login", new { area = "" }, new { @class = "nav-link" })</li>
                    </ul>
                </div>
            </div>
        </nav>
        <div class="container-fluid col-sm-12 body-content flex-grow-1 mt-5">
            @RenderBody()
        </div>
        <footer class="footer text-center mt-auto">
            <div class="container">
                <p class="fst-italic mb-3 mt-3">&copy; @DateTime.Now.Year - Registro de la Vittopropiedad Inmueble - Corrientes - Argentina.</p>
            </div>
        </footer>
        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </body>
</html>

Views/Shared/_LoginLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Inicio de Sesión</title>
    @Styles.Render("~/Content/css")
    @Styles.Render("~/Content/login")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="container-fluid col-xxl-8 col-xl-9 col-lg-10 col-md-11 col-sm-12 body-content mb-5">
        @RenderBody()
    </div>
    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>